# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
      <nixpkgs/nixos/modules/profiles/qemu-guest.nix>
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "nbd" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ pkgs.nbd ];
  boot.initrd.kernelModules = [ "nbd" ];

  # fileSystems."/" =
  #   { device = "/dev/disk/by-uuid/2752fecc-c9f9-48a5-b0e2-e304eb4b7e14";
  #     fsType = "ext4";
  #   };

  # swapDevices =
  #   [ { device = "/dev/disk/by-uuid/dbeafdfb-2e54-4baa-bdaf-cb1e290b4600"; }
  #   ];

  # fileSystems."/media/VBoxFS" = {
  #   fsType = "vboxsf";
  #   device = "Environment";
  #   options = "rw";
  # };

  fileSystems."/export/projects" = {
    device = "/home/fms-dev/Projects";
    options = [ "bind" ];
  };

  services.nfs.server.enable = true;
  services.nfs.server.exports = pkgs.lib.readFile /usr/etc/exports;

}
