# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];


  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sr_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e2fadb96-4a7e-4d0c-910d-398a1f08d28e";
      fsType = "xfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1d3bb1fd-0995-48ce-a99f-1bf771e30827";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/a44b9c72-b7a3-4205-8137-0fccc26fcaf8"; }
    ];

  console = {
    font = "Lat2-Terminus16";
    keyMap = "jp106";
  };

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  hardware.bluetooth.enable = true;

  # Enable sound.
  # sound.enable = true;
  # sound.mediaKeys.enable = true;
  # sound.mediaKeys.volumeStep = "5%";

  hardware.opengl.enable = true;

  # Whether to enable Auto toggle keyboard back-lighting on Thinkpads (and maybe other laptops) for Linux.
  services.tp-auto-kbbl.enable = false;

  # for VirtualBox
  # networking.interfaces.enp0s8.ip4 = [ { address = "192.168.56.100"; prefixLength = 24; } ];
}
